name: Docker Release (tagged)

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Parse version sections from git tag
        run: |
          if [[ ${{ github.ref_name }} =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "version_major=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            echo "version_minor=${BASH_REMATCH[2]}" >> $GITHUB_ENV
            echo "version_patch=${BASH_REMATCH[3]}" >> $GITHUB_ENV
          else
            echo "Invalid tag format"
            exit 1
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            thsmdt/sonarqube-qualitygate-check:${{ env.version_major }}
            thsmdt/sonarqube-qualitygate-check:${{ env.version_major }}.${{ env.version_minor }}
            thsmdt/sonarqube-qualitygate-check:${{ env.version_major }}.${{ env.version_minor }}.${{ env.version_patch }}
            thsmdt/sonarqube-qualitygate-check:latest
